# Generated by Django 4.1.3 on 2023-01-06 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cie10',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigoCie10', models.CharField(max_length=20)),
                ('descripcion', models.CharField(max_length=350)),
            ],
        ),
        migrations.CreateModel(
            name='ImagenesRecobros',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facturaips', models.CharField(max_length=40)),
                ('nombreImagen', models.ImageField(upload_to='media/media/')),
                ('fechaCreacion', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='InformacionUsuarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipodoc', models.CharField(max_length=20)),
                ('numdocumento', models.CharField(max_length=22)),
                ('primerNombre', models.CharField(max_length=100)),
                ('segundoNombre', models.CharField(max_length=100)),
                ('primerApellido', models.CharField(max_length=100)),
                ('segundoApellido', models.CharField(max_length=100)),
                ('tipoAfiliado', models.CharField(max_length=20)),
                ('estadoAfiliacion', models.CharField(max_length=50)),
                ('feInicio', models.DateField()),
                ('fefinal', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='RecobrosDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipodoc', models.CharField(max_length=20)),
                ('numdocumento', models.CharField(max_length=22)),
                ('numactaCtc', models.CharField(max_length=40)),
                ('feacta', models.DateField()),
                ('facturaips', models.CharField(max_length=50)),
                ('fechaPrestacion', models.DateField()),
                ('codtecnologia', models.CharField(max_length=40)),
                ('nitprestador', models.IntegerField()),
                ('cie10', models.CharField(max_length=7)),
                ('cantidad', models.IntegerField()),
                ('valorunit', models.IntegerField()),
                ('valfacturado', models.IntegerField()),
                ('copago', models.IntegerField()),
                ('valliquidado', models.IntegerField()),
                ('codhomologo', models.CharField(max_length=30)),
                ('valorunith', models.IntegerField()),
                ('valorhomologo', models.IntegerField()),
                ('idsuministro', models.IntegerField()),
                ('radanterior', models.IntegerField()),
                ('itemanterior', models.IntegerField()),
                ('radicadoApf', models.IntegerField()),
                ('feauditoria', models.DateField()),
                ('numfallo', models.CharField(max_length=50)),
                ('fefallo', models.DateField()),
                ('numAutoridadJudicial', models.CharField(max_length=200)),
                ('tipoautoridadjudicial', models.CharField(max_length=200)),
                ('codcausal', models.IntegerField()),
                ('codigodane', models.CharField(max_length=10)),
                ('imgmipres', models.CharField(max_length=100)),
                ('imgctc', models.CharField(max_length=100)),
                ('imgfactura', models.CharField(max_length=100)),
                ('imgevidencia', models.CharField(max_length=100)),
                ('imgformula', models.CharField(max_length=100)),
                ('imgotros', models.CharField(max_length=100)),
            ],
        ),
    ]
