# Generated by Django 4.1.3 on 2022-12-15 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RecobrosDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipodoc', models.CharField(max_length=20)),
                ('numdocumento', models.CharField(max_length=22)),
                ('numactaCtc', models.CharField(max_length=40)),
                ('feacta', models.DateField()),
                ('facturaips', models.CharField(max_length=50)),
                ('fechaPrestacion', models.DateField()),
                ('codtecnologia', models.CharField(max_length=40)),
                ('nitprestador', models.IntegerField()),
                ('cie10', models.CharField(max_length=7)),
                ('valfacturado', models.IntegerField()),
                ('copago', models.IntegerField()),
                ('valliquidado', models.IntegerField()),
                ('codhomologo', models.CharField(max_length=30)),
                ('cantidad', models.IntegerField()),
                ('valorunit', models.IntegerField()),
                ('valorhomologo', models.IntegerField()),
                ('idsuministro', models.IntegerField()),
                ('radanterior', models.IntegerField()),
                ('itemanterior', models.IntegerField()),
                ('radicadoApf', models.IntegerField()),
                ('feauditoria', models.DateField()),
                ('numfallo', models.CharField(max_length=50)),
                ('fefallo', models.DateField()),
                ('numAutoridadJudicial', models.CharField(max_length=200)),
                ('tipoautoridadjudicial', models.CharField(max_length=200)),
                ('codcausal', models.IntegerField()),
                ('codigodane', models.CharField(max_length=10)),
                ('imgmipres', models.CharField(max_length=100)),
                ('imgctc', models.CharField(max_length=100)),
                ('imgfactura', models.CharField(max_length=100)),
                ('imgevidencia', models.CharField(max_length=100)),
                ('imgformula', models.CharField(max_length=100)),
                ('imgotros', models.CharField(max_length=100)),
            ],
        ),
    ]
