# Generated by Django 4.1.3 on 2023-01-09 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recobros', '0002_recobrosdetalle_idusuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='recobrosdetalle',
            name='deschomologo',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='recobrosdetalle',
            name='desctecnologia',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
