# Generated by Django 4.1.3 on 2023-01-09 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recobros', '0004_recobrosdetalle_tipotecnologia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recobrosdetalle',
            name='codcausal',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='recobrosdetalle',
            name='codigodane',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='recobrosdetalle',
            name='fefallo',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='recobrosdetalle',
            name='idusuario',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='recobrosdetalle',
            name='imgctc',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='recobrosdetalle',
            name='imgevidencia',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='recobrosdetalle',
            name='imgfactura',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='recobrosdetalle',
            name='imgformula',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='recobrosdetalle',
            name='imgmipres',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='recobrosdetalle',
            name='imgotros',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='recobrosdetalle',
            name='numAutoridadJudicial',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='recobrosdetalle',
            name='numfallo',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='recobrosdetalle',
            name='tipoautoridadjudicial',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
