# Generated by Django 4.1.3 on 2023-01-09 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recobros', '0005_alter_recobrosdetalle_codcausal_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recobrosdetalle',
            name='codigodane',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='recobrosdetalle',
            name='deschomologo',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='recobrosdetalle',
            name='desctecnologia',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='recobrosdetalle',
            name='idusuario',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='recobrosdetalle',
            name='imgctc',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='recobrosdetalle',
            name='imgevidencia',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='recobrosdetalle',
            name='imgfactura',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='recobrosdetalle',
            name='imgformula',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='recobrosdetalle',
            name='imgmipres',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='recobrosdetalle',
            name='imgotros',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='recobrosdetalle',
            name='numAutoridadJudicial',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='recobrosdetalle',
            name='numfallo',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='recobrosdetalle',
            name='tipoTecnologia',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='recobrosdetalle',
            name='tipoautoridadjudicial',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
