# Generated by Django 4.1.3 on 2023-01-09 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recobros', '0006_alter_recobrosdetalle_codigodane_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recobrosdetalle',
            name='codhomologo',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='recobrosdetalle',
            name='valorhomologo',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='recobrosdetalle',
            name='valorunith',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
