# Generated by Django 3.2.15 on 2022-11-28 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tiporecobro', models.CharField(blank=True, db_column='tipoRecobro', max_length=50, null=True)),
                ('regimen', models.CharField(blank=True, db_column='Regimen', max_length=20, null=True)),
                ('descripcionrecobro', models.CharField(blank=True, db_column='DescripcionRecobro', max_length=50, null=True)),
                ('numerofactura_recobro', models.CharField(blank=True, db_column='NumeroFactura_recobro', max_length=20, null=True)),
                ('nitprestador', models.IntegerField(blank=True, db_column='NitPrestador', null=True)),
                ('nombreprestador', models.CharField(blank=True, db_column='Nombreprestador', max_length=150, null=True)),
                ('fechaprestacion', models.DateField(blank=True, db_column='FechaPrestacion', null=True)),
                ('departamento', models.CharField(blank=True, db_column='Departamento', max_length=80, null=True)),
                ('municipio', models.CharField(blank=True, db_column='Municipio', max_length=80, null=True)),
                ('tipodocumentousuario', models.CharField(blank=True, db_column='TipoDocumentoUsuario', max_length=40, null=True)),
                ('identificacionusuario', models.CharField(blank=True, db_column='IdentificacionUsuario', max_length=20, null=True)),
                ('codtecnologia', models.CharField(blank=True, db_column='CodTecnologia', max_length=20, null=True)),
                ('nombretecnologia', models.CharField(blank=True, db_column='NombreTecnologia', max_length=400, null=True)),
                ('cantidad', models.IntegerField(blank=True, db_column='Cantidad', null=True)),
                ('valorunit', models.IntegerField(blank=True, db_column='Valorunit', null=True)),
                ('valfacturado', models.IntegerField(blank=True, db_column='Valfacturado', null=True)),
                ('numeromipres_actactc', models.CharField(blank=True, db_column='NumeroMipres_ActaCtc', max_length=30, null=True)),
            ],
            options={
                'db_table': 'inventario',
                'managed': False,
            },
        ),
    ]
