# Generated by Django 4.1.3 on 2022-11-29 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventariorecobro', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prestadoressuludvida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nitprestador', models.IntegerField()),
                ('nombreprestador', models.CharField(max_length=400)),
            ],
        ),
    ]
